### PR TITLE
More SQL-based anonymization

### PR DESCRIPTION
**Pull request by seancolsen**
This PR doesn't change anything yet. So far just adding this library which is good at generating SQL that makes random stuff. 

More commits coming soon which will be based on this work.

### CODE REVIEW

**Comment by xurizaemon** [comment]
This looks really good!

**Comment by xurizaemon** [comment]
Let me know when you want me to give this a test?

**Comment by seancolsen** [comment]
Ready for testing now :slightly_smiling_face:

**Comment by seancolsen** [comment]
I'm continuing to push more commits, but you can test this any time. I'm always leaving it in a state where it works (just adding things to make it do more).

**Comment by seancolsen** [comment]
Ok @xurizaemon at this point I'm going to chill out and wait for feedback from you before proceeding with any more changes. 

This PR should now *fully* anonymize the entire DB with the "random" strategy (i.e. give contacts names like "Kmosipb Hgaln" and do *lots* more stuff). When I run this on a DB with ~80k contacts, it takes about two minutes on my laptop. Not bad. I'm hitting a *lot* of fields here. I really combed through the schema to look for places I thought might contain personal data. For example, I chose to truncate `civicrm_note` because notes often contain names. Think the scope of the anonymization is pretty comprehensive. And if we want to process more fields, it should be easy to add them.

**Pull request merged**
